service: quiz

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    JWT_SECRET: mySecretKey

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/quizUsersDb
            - arn:aws:dynamodb:${self:provider.region}:*:table/quizUsersDb/index/UsernameIndex
            - arn:aws:dynamodb:${self:provider.region}:*:table/quizDB

functions:
  getAllUsers:
    handler: functions/admin/getAllUsers/index.handler
    events:
      - http:
          path: users
          method: get

  getAllQuiz:
    handler: functions/admin/getAllQuiz/index.handler
    events:
      - http:
          path: quizzes
          method: get

  signup:
    handler: functions/user/signup.handler
    events:
      - http:
          path: signup
          method: post

  login:
    handler: functions/user/login.handler
    events:
      - http:
          path: login
          method: post

  postQuiz:
    handler: functions/postQuiz.handler
    events:
      - http:
          path: quiz
          method: post

  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: DELETE

  postQuestion:
    handler: functions/postQuestion/index.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: POST

  getQuiz:
    handler: functions/getQuiz/index.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: GET

resources:
  Resources:
    quizUsersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quizUsersDb
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    quizDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quizDB
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
